---
- hosts: worker-nodes
  become: True
  vars:
    - packages: ["git","nginx"]
  tasks:
   - name: Installing {{ packages }} on {{ worker-nodes }}
     yum:
      name: "{{item}}"
      state: present
     with_items: "{{packages}}"
      
